#!/bin/bash
INIT=configured
if [ ! -f "$INIT" ]
then
	exit 1
fi

cd old
FILE=.bash_aliases
rm ~/$FILE
if [ -f "$FILE" ]
then
	cp $FILE ~
	rm $FILE
fi

FILE=.gitconfig
rm ~/$FILE
if [ -f "$FILE" ]
then
	cp $FILE ~
	rm $FILE
fi
cd ..
rm -r old
rm $INIT
