#!/bin/bash
INIT=initialized
if [ ! -f "$INIT" ]
then
	exit 1
fi

#continue
cd old
FILE=.bash_aliases
if [ -f "$FILE" ]
then
	rm ~/$FILE
	mv $FILE ~/$FILE
fi

FILE=.gitconfig
if [ -f "$FILE" ]
then
	rm ~/$FILE
	mv $FILE ~/$FILE
fi

FILE=.vimrc
if [ -f "$FILE" ]
then
	rm ~/$FILE
	mv $FILE ~/$FILE
fi

cd ..
rm -r old
rm $INIT
