#!/bin/bash
INIT=initialized
if [ -f "$INIT" ]
then
	echo "re-initing and exiting"
	exec bash
	exit 1
fi

#check if zsh is used
if [ -f ~/.zshrc ]
then
	echo "source $HOME/.bash_aliases" >> ~/.zshrc
	echo "source $HOME/.zsh_plugins" >> ~/.zshrc
fi

#continue
mkdir old
cd ~
FILE=.bash_aliases
if [ -f "$FILE" ]
then
	mv $FILE config/old/$FILE
fi
ln -s config/$FILE .

FILE=.gitconfig
if [ -f "$FILE" ]
then
	mv $FILE config/old/$FILE
fi
ln -s config/$FILE .

FILE=.vimrc
if [ -f "$FILE" ]
then
	mv $FILE config/old/$FILE
fi
ln -s config/$FILE .

FILE=.zsh_plugins
if [ -f "$FILE" ]
then
	mv $FILE config/old/$FILE
fi
ln -s config/$FILE .

cd config
touch $INIT
exec bash

