#!/bin/bash
INIT=configured
if [ -f "$INIT" ]
then
	echo "re-initing and exiting"
	exec bash
	exit 1
fi

mkdir old
cd ~
FILE=.bash_aliases
if [ -f "$FILE" ]
then
	mv $FILE config/old/$FILE
fi
ln -s config/$FILE .

FILE=.gitconfig
if [ -f "$FILE" ]
then
	mv $FILE config/old/$FILE
fi
ln -s config/$FILE .

touch config/$INIT
exec bash

